services:
  main-nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites:/etc/nginx/sites
      - ./html:/usr/share/nginx/html
      - /dev/null:/etc/nginx/conf.d/default.conf
    ports:
      - "8085:80"
    depends_on:
      - plugin-site1
      - plugin-site2
      - plugin-widget1
      - plugin-widget2
      - plugin-widget3
      - plugin-widget4
      - plugin-widget5
      - plugin-widget-cook

  plugin-site1:
    build: ./plugin/site1
    expose:
      - "80"
    container_name: plugin-site1

  plugin-site2:
    build: ./plugin/site2
    expose:
      - "80"
    container_name: plugin-site2

  plugin-widget1:
    build: ./plugin/widget1
    expose:
      - "80"
    container_name: plugin-widget1
  plugin-widget2:
    build: ./plugin/widget2
    expose:
      - "80"
    container_name: plugin-widget2
  plugin-widget3:
    build: ./plugin/widget3
    expose:
      - "80"
    container_name: plugin-widget3
  plugin-widget4:
    build: ./plugin/widget4
    expose:
      - "80"
    container_name: plugin-widget4
    
  plugin-widget5:
    build: ./plugin/widget5
    expose:
      - "80"
    container_name: plugin-widget5
    
  plugin-widget-cook:
    build: ./plugin/widget-cook
    expose:
      - "80"
    container_name: plugin-widget-cook